name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run build
      - name: Uploading
        uses: actions/upload-artifact@v4
        with:
          name: mozilla-vpn-extension-unsigned.xpi
          path: dist/
  lint:
    name: Check Linting
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run lint

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install
      - run: npm run test

  prComplete:
    runs-on: ubuntu-latest
    needs: [test, build, lint]
    name: Pr Complete
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: echo "Good JOB!"

  deploy:
    name: Put XPI on Github Page
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: prComplete
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - run: mv .github/_site _site
      - name: Download a Addons Artifact
        uses: actions/download-artifact@v4
        with:
          name: mozilla-vpn-extension-unsigned.xpi
          path: _site/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
